[package]
name = "ironbar-todo"
version = "0.1.1"
edition = "2024"
authors = ["Junaid Sultan <contact@junaidsultan.com>"]
description = "Simple todo widget for ironbar with daily tasks"
licence = "MIT"
repository = "https://github.com/junaidsultanxyz/ironbar-todo"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
gtk4 = "0.11.5"
gtk4-layer-shell = "0.8.1"
todo = { git = "https://github.com/junaidsultanxyz/todo-rust", version = "0.1.1" }
